### PR TITLE
Add compatibility for parsing ARD c3 metadata

### PR DESCRIPTION
**Pull request by james-blitzm**
Resolves STAC parsing for ARD c3 metadata.

### CODE REVIEW

**Comment by alexgleith** [comment]
This won't work for what you're doing, @james-blitzm.

Because the lookup for `sentinel-2` is naming the product too...

I think that this code path should not be running if there's an `odc:product` set.

**Comment by alexgleith** [comment]
> Resolves STAC parsing for ARD c3 metadata.

This isn't what this PR does. You're trying to get a Sentinel-2 derivative product able to be parsed.

**Comment by uchchwhash** [comment]
I don't see what the way forward here is besides this @alexgleith, we are trying to enable the burn area product to be indexed, and it derives from sentinel-2 ARD and therefore is inherits that tag there. We confirmed that our provisional sentinel-2 ARD product (unfortunately) has the tag there. So I think @james-blitzm is correct in that this enables parsing the ARD product too, as well as the burn area product.

**Comment by uchchwhash** [comment]
Sorry @alexgleith I see what you mean. Note to self: check before you post.

**Comment by uchchwhash** [comment]
Superseded by https://github.com/opendatacube/odc-tools/pull/406.

**Pull request closed without merging**
