### PR TITLE
Fix s3 to dc indexing issue

### LINKED ISSUE #256: s3-to-dc fail on doing stac_transform
I don't know how to reproduce the failure yet...

```
index-sentinel-2-3909406840: Traceback (most recent call last):
index-sentinel-2-3909406840:   File "/env/lib/python3.8/site-packages/odc/index/_index.py", line 67, in parse_doc_stream
index-sentinel-2-3909406840:     metadata = transform(metadata)
index-sentinel-2-3909406840:   File "/env/lib/python3.8/site-packages/odc/index/stac.py", line 280, in stac_transform
index-sentinel-2-3909406840:     if pixel_size < 0:
index-sentinel-2-3909406840: TypeError: '<' not supported between instances of 'NoneType' and 'int'
index-sentinel-2-3909406840: During handling of the above exception, another exception occurred:
index-sentinel-2-3909406840: Traceback (most recent call last):
index-sentinel-2-3909406840:   File "/env/bin/s3-to-dc", line 8, in <module>
index-sentinel-2-3909406840:     sys.exit(cli())
index-sentinel-2-3909406840:   File "/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
index-sentinel-2-3909406840:     return self.main(*args, **kwargs)
index-sentinel-2-3909406840:   File "/env/lib/python3.8/site-packages/click/core.py", line 782, in main
index-sentinel-2-3909406840:     rv = self.invoke(ctx)
index-sentinel-2-3909406840:   File "/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
index-sentinel-2-3909406840:     return ctx.invoke(self.callback, **ctx.params)
index-sentinel-2-3909406840:   File "/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
index-sentinel-2-3909406840:     return callback(*args, **kwargs)
index-sentinel-2-3909406840:   File "/env/lib/python3.8/site-packages/odc/apps/dc_tools/s3_to_dc.py", line 165, in cli
index-sentinel-2-3909406840:     added, failed = dump_to_odc(
index-sentinel-2-3909406840:   File "/env/lib/python3.8/site-packages/odc/apps/dc_tools/s3_to_dc.py", line 47, in dump_to_odc
index-sentinel-2-3909406840:     for uri, metadata in uris_docs:
index-sentinel-2-3909406840:   File "/env/lib/python3.8/site-packages/odc/index/_index.py", line 70, in parse_doc_stream
index-sentinel-2-3909406840:     on_error(uri, doc, e)
index-sentinel-2-3909406840: TypeError: 'Index' object is not callable
```

### PR DESCRIPTION
**Pull request by alexgleith**
Should fix #256

### CODE REVIEW

**Comment by jeremyh** [comment]
From my reading of the api, without a callback it's going to swallow all errors without any indication that they happened

I'd be in favour of at least a log message or something. 

Or better: change `parse_doc_stream` itself to either log or reraise the exception as its default behaviour. It feels like a dangerous default currently.

**Comment by jeremyh** [comment]
Here's other usage of the function:
https://github.com/opendatacube/odc-tools/blob/566cf5a136bcd8a5a405ba7696ca02ac7c8ecc84/libs/index/odc/index/_index.py#L88-L96

**Review by jeremyh — APPROVED** [review]
:+1:

**Comment by alexgleith** [comment]
Thanks, @jeremyh

**Pull request merged**
