### PR TITLE
Add new dc-sync-products tool including tests and integration tests

### PR DESCRIPTION
**Pull request by alexgleith**
* Adds a little tool that will add or update product definitions based on a CSV list
* Adds a stac_to_dc tests, which is skipped, because we have library dependency issues (see #274)
* Fixes Dockerfile to remove `odc` user and simplify file system things
* Changes some of the image building and test running to handle code in `/code` changing between image building and test running

### CODE REVIEW

**Review by whatnick — COMMENTED** [review]
Some whitespace changes presumably from black ? Can we add a pre-commit here to standardize the code linting ? Seems like there is a bit of a dependency hell you re stuck in. Let me know if I can help / pair in some way over the next few days.

**Comment by alexgleith** [comment]
The hell I'm in is Docker and pip on CI.

My feeling right now is that it's over complicated...

**Comment by alexgleith** [comment]
If someone can explain why, after manually installing a local version of the tools, the commands are still unavailable, I'll be very happy!

```
Successfully installed odc-aio-0.1.dev1089+g3addafe odc-algo-0.1.dev1089+g3addafe odc-apps-cloud-0.1.dev1089+g3addafe odc-apps-dc-tools-0.1.dev1089+g3addafe odc-aws-0.1.dev1089+g3addafe odc-azure-0.1.dev1089+g3addafe odc-dscache-0.1.dev1089+g3addafe odc-dtools-0.1.dev1089+g3addafe odc-geom-0.1.dev1089+g3addafe odc-index-0.1.dev1089+g3addafe odc-io-0.1.dev1089+g3addafe odc-ppt-0.1.dev1089+g3addafe odc-stats-0.1.dev1089+g3addafe odc-thredds-0.1.dev1089+g3addafe odc-ui-0.1.dev1089+g3addafe
WARNING: You are using pip version 21.1.3; however, version 21.2.1 is available.
You should consider upgrading via the '/env/bin/python -m pip install --upgrade pip' command.
/home/runner/work/_temp/ad109d15-d58e-465a-a610-86905d5b58a1.sh: line 5: dc-sync-products: command not found
```

**Comment by alexgleith** [comment]
Ok, this is ready for review now @whatnick. The normal test CI will fail, but the bigger one that builds the image will pass. And I'll ensure that the tests pass with the rebuilt test image.

**Comment by whatnick** [comment]
The fundamental issue I have with the tests here is that the CI is dog-fooding a tool being tested as part of the test infrastructure / fixture. While it should fundamentally follow the principle of test-isolation and setup the fixture using mechanisms other than the scripts being tested. If we must dogfood tests ... i.e. run some tools to setup the DB in a state that other tools can run then I suggest we use a [pytest-depends](https://pypi.org/project/pytest-depends/) mechanism.

**Review by whatnick — CHANGES_REQUESTED** [review]
See notes around pytest-depends

**Comment by alexgleith** [comment]
Added pytest-depends :-)

**Pull request merged**
