### PR TITLE
use geobox to add geometry to product metadata

### PR DESCRIPTION
**Pull request by supermarkion**
This PR aims to fix the odc-stats `apply-eodatasets3` dump the incorrect inherit_geometry in metadata files. It used to `inherit_geometry` from source dataset, which is incorrect.

Before this PR, the output [stac.json](https://dea-public-data-dev.s3-ap-southeast-2.amazonaws.com/ga_ls8c_nbart_gm_cyear_3/3-0-0/x06/y25/2019--P1Y/ga_ls8c_nbart_gm_cyear_3_x06y25_2019--P1Y_final.stac-item.json) has 

```json
"geometry": {
  "type": "Polygon",
  "coordinates": [
    [
      [
        136.87431877083844,
        -27.118138627189573
      ],
      [
        136.8733821058028,
        -27.11798250120694
      ],
      [
        137.0471886637439,
        -26.318537446421956
      ],
      [
        137.19975163682776,
        -25.60984260498856
      ],
      [
        137.24337985928196,
        -25.405900173664996
      ],
      [
        137.24403219661377,
        -25.403903084748038
      ],
      [
        137.24477227589796,
        -25.40401898180104
      ],
      [
        137.24486903760283,
        -25.403935093995887
      ],
      [
        137.28473367933609,
        -25.410593397062318
      ],
      [
        137.30066887978433,
        -25.413212985883522
      ],
      [
        137.92649310047318,
        -25.5161631008849
      ],
      [
        139.14701091560525,
        -25.708515773575712
      ],
      [
        139.14699529106443,
        -25.7085880171462
      ],
      [
        139.14781139761598,
        -25.708717325747582
      ],
      [
        139.14789339280756,
        -25.70937435659971
      ],
      [
        138.80723853485412,
        -27.427919688090153
      ],
      [
        138.80648410291977,
        -27.427990421763976
      ],
      [
        138.80460034726102,
        -27.42770294912283
      ],
      [
        138.8031322499076,
        -27.42767288892519
      ],
      [
        138.77890323318206,
        -27.423974887616716
      ],
      [
        136.87433170032395,
        -27.11820064244745
      ],
      [
        136.87431877083844,
        -27.118138627189573
      ]
    ]
  ]
}
```

After fix it, the geometry is 
```json
"geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    110.57624161412032,
                    -25.855827452110635
                ],
                [
                    110.41324671827235,
                    -26.699762082593157
                ],
                [
                    111.37711372897705,
                    -26.8405062825054
                ],
                [
                    111.53308872366085,
                    -25.995569980342225
                ],
                [
                    110.57624161412032,
                    -25.855827452110635
                ]
            ]
        ]
    }
```

### CODE REVIEW

**Comment by supermarkion** [comment]
The missing `proj:shape` and `proj:transform` in STAC.json will be handle in `EODatasets3` side: https://github.com/opendatacube/eo-datasets/pull/216

**Review by omad — APPROVED** [review]
This looks great, thank you Sai, sorry I didn't see it sooner.

A couple of extra notes:
- this bug was causing all output datasets to have completely incorrect geometry, it appeared to be treating UTM coordinates as Australian Albers coordinates.
- One of the features that eo-datasets can provide, is creating pixel precise bounding geometries. This change disables that, and brings it in line with the metadata generation through `pystac` directly. Most statistics fill an entire image anyway, it's only around the boundaries of observation areas that might not fill an image.

**Comment by supermarkion** [comment]
> This looks great, thank you Sai, sorry I didn't see it sooner.
> 
> A couple of extra notes:
> 
> * this bug was causing all output datasets to have completely incorrect geometry, it appeared to be treating UTM coordinates as Australian Albers coordinates.
> * One of the features that eo-datasets can provide, is creating pixel precise bounding geometries. This change disables that, and brings it in line with the metadata generation through `pystac` directly. Most statistics fill an entire image anyway, it's only around the boundaries of observation areas that might not fill an image.

Thanks a lot to the extra tech detail/background.

**Comment by supermarkion** [comment]
> This looks great, thank you Sai, sorry I didn't see it sooner.
> 
> A couple of extra notes:
> 
> * this bug was causing all output datasets to have completely incorrect geometry, it appeared to be treating UTM coordinates as Australian Albers coordinates.
> * One of the features that eo-datasets can provide, is creating pixel precise bounding geometries. This change disables that, and brings it in line with the metadata generation through `pystac` directly. Most statistics fill an entire image anyway, it's only around the boundaries of observation areas that might not fill an image.

Thanks a lot to the extra tech detail/background.

**Pull request merged**
