### PR TITLE
update masking to support third argument

### PR DESCRIPTION
**Pull request by NikitaGandhi**
update masking lib to support third argument so the operation can be performed in this order:
- morphological closing with r3 (>0)
- then opening with r1 (>0)
- followed by dilation with r2 (>0)

Doing this will fixes:
- overlap issue as the whole masking operation is performed using single dask task

### CODE REVIEW

**Review by cbur24 — APPROVED** [review]

**Comment by robbibt** [comment]
I wonder if we should consider renaming the arguments to make them clearer than `r1, r2, r3`, e.g. `opening, dilation, closing` (or ideally, reordering them too so that they follow the order they are run: `closing, opening, dilation`).

**Comment by NikitaGandhi** [comment]
- Updated filter to dict instead of tuple. Use `0` if you want to omit the specific operation. It is backward compatible and support below options.
Usage: 
**dict(closing=2, opening=1, dilation=1)** - produce xx["mask_band_2_1_1"]
**dict(opening=1, dilation=1)** - produce xx["mask_band_1_1"]

- Updated stats gm implementation filter definition to dict - no impact
- Updated pq implementation filter definition to dict - no impact

**Review by cbur24 — APPROVED** [review]
Nice, this should help limit the confusion with the morphological operators

**Review by robbibt — APPROVED** [review]
Looks great to me!

**Review by kieranricardo — APPROVED** [review]
looks good!

**Comment by NikitaGandhi** [comment]
Thanks @Kirill888. As this PR was closed already, I have incorporated this change into this PR https://github.com/opendatacube/odc-tools/pull/298

**Pull request merged**
